name: quiz_shower
description: QuizShower
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  cloud_functions: ^4.4.1
  firebase_auth: ^4.10.0
  logger: ^2.0.2+1
  firebase_ui_auth: ^1.8.0
  firebase_ui_localizations: ^1.6.1
  firebase_core_platform_interface: ^4.8.0
  hooks_riverpod: ^2.4.3
  flutter_hooks: ^0.20.2
  freezed_annotation: ^2.4.1
  freezed: ^2.4.3
  url_launcher: ^6.1.14
  riverpod_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.3
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-SemiBold.ttf
